### ISSUE TITLE
config options are cached

### ISSUE THREAD

**Issue by autumnwoodberry** [LinusBorg/vue-cli-plugin-test-attrs#10]
Probably related to https://github.com/LinusBorg/vue-cli-plugin-test-attrs/issues/3

Changing the `attrs` option in the config appears to be cached. Changing it has no effect until I reinstall node modules.

**Comment by LinusBorg** [comment]
Good catch.

Can be fixed by including the options from vue.config.js here:

https://github.com/LinusBorg/vue-cli-plugin-test-attrs/blob/develop/index.js#L34
