### ISSUE TITLE
process.env properties are undefined when used with modes

### ISSUE THREAD

**Issue by autumnwoodberry** [LinusBorg/vue-cli-plugin-test-attrs#9]
Adding the `VUE_CLI_KEEP_TEST_ATTRS` to a `.env.mode` file and loading it with `--mode mode` does not work. The `process.env.VUE_CLI_KEEP_TEST_ATTRS` and `process.env.NODE_ENV` are `undefined`.

Moving the check into the main function solves this issue but I'm not sure if there are any other consequences from doing that - seems like it should be fine though.

Adding the variable directly (using `VUE_CLI_KEEP_TEST_ATTRS=true vue-cli-service build` for example) work just fine.

**Comment by LinusBorg** [comment]
Hey @autumnwoodberry, 

only saw this now, apologies.

>  The process.env.VUE_CLI_KEEP_TEST_ATTRS and process.env.NODE_ENV are undefined.

Where are they undefined?

**Comment by autumnwoodberry** [comment]
@LinusBorg 

At this point https://github.com/LinusBorg/vue-cli-plugin-test-attrs/blob/develop/index.js#L13-L19 both the `process.env.VUE_CLI_KEEP_TEST_ATTRS` and `process.env.NODE_ENV` are `undefined`.

**Comment by LinusBorg** [comment]
Right, I have to move those into the plugin function. Thanks!
